-- Execute este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.boat_assignments (
  id bigint generated by default as identity primary key,
  week_start date not null,
  day_key text not null check (day_key in ('tue', 'wed', 'thu', 'fri')),
  time_key text not null check (time_key in ('06:30', '07:30')),
  boat_key text not null check (boat_key in ('4x', '2x', 'skiff-yellow', 'skiff-red', 'caravela')),
  seat_index integer not null check (seat_index between 0 and 3),
  side text null check (side is null or side in ('BB', 'BE')),
  athlete_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start, day_key, time_key, boat_key, seat_index)
);

alter table public.boat_assignments enable row level security;

-- Sem login: visitantes anônimos podem consultar e alterar a escala.
-- Isso é intencional para este projeto. Qualquer pessoa com o link poderá editar.
drop policy if exists "public can read assignments" on public.boat_assignments;
create policy "public can read assignments"
on public.boat_assignments for select
to anon, authenticated
using (true);

drop policy if exists "public can insert assignments" on public.boat_assignments;
create policy "public can insert assignments"
on public.boat_assignments for insert
to anon, authenticated
with check (true);

drop policy if exists "public can update assignments" on public.boat_assignments;
create policy "public can update assignments"
on public.boat_assignments for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public can delete assignments" on public.boat_assignments;
create policy "public can delete assignments"
on public.boat_assignments for delete
to anon, authenticated
using (true);

-- Habilita atualizações em tempo real entre navegadores.
alter publication supabase_realtime add table public.boat_assignments;
